apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: DT
  namespace: DT-$ENV
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: DT